### ISSUE TITLE
Confirmed malaria cases in Madagascar Epi Report

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#102]
it seems that the indicator "Malaria confirmed by rapid test or slide" reported in "2.3 Other diseases and events of public health importance" is not reflecting correctly.

It currently lists 0 cases (up to 8 June). However there are 8 malaria cases in the system - 7 are confirmed positive by RDT (cd./malaria_rdt = positive) and 1 by Slide (cd./malaria_slide = positive), so it should be listing 7.

Could we please check?

**Comment by mrjb** [comment]
This should be sorted and will be included in the next deployment.
