### ISSUE TITLE
Enhanced dashboard features

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#103]
To look at enhancing dashboard features, including:
1. Removing This Week (Orange) columns from **Demographics Tab** charts
2. Enhancing chart in **Communicable Diseases Tab** to show rows of non-zero diseases with line chart for each to display trends over time
3. To display the **Alerts Tab** summary by location and not disease

**Comment by mixmixmix** [comment]
Hi @johnhaskew:
Could you clarify point 2, please? 
Do you mean _to remove zero-count diseases from the **Communicable Diseases Tab**_ and _replace existing bar chart with a line chart_ (the one which appears on a new page after clicking on a disease).

**Comment by mixmixmix** [comment]
@johnhaskew, could you clarify the above?

**Comment by Gulfa** [comment]
@mixmixmix: We will come back to this in a bit later on.
