### ISSUE TITLE
Madagascar Reports Issues

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#106]
**Notifications Tab:**

1. To please update notifications tab to reflect the Madagascar reports that are showing in the system (it currently shows NCD etc).

**Reports Tab:**

1. The Communicable Disease Profile Report is currently named Public Health Profile Report in the menu drop down of the Reports Tab. To please rename and update.

2. To please rename the Weekly Epidemiological Monitoring Report just Epidemiological Monitoring Report.

**Madagascar Communicable Disease Profile Report**

1. To please remove “0.0% nationals and 0.0% refugee status” line in Key Findings of Madagascar Communicable Disease Profile Report

2. To please rename Key findings -> Key Findings (capitalisation of F)

3. To please rename the first sentence of Key Findings:
“Information reported in this communicable disease profile represents cases reported from 58 reporting sites in Madagascar between X and X.”

4. To rename the sentence in Alerts:
“A total of 1 alerts generated between X and X.”

5. To please remove the following in Public Health Indicators”
2	Laboratory results recorded	0.0%	0
3	Prescribing practice recorded	0.0%	0

6. To please include Completeness as an indicator in Public Health Indicators, so it will show:
1	Cases Reported		100.0%	196
2	Alerts generated	100.0%	1
3	Alerts investigated	100.0%	1
4	Completeness		X%

**Madagascar Communicable Diseases Report**

1. To please rename the report "Communicable Disease Report" (remove the s from diseases)

2. To please remove the "this week" in the sentences beneath each disease graph and include "between X and X", so as to read:
There were no new confirmed cases and no new suspected cases of X between X and X.

**All Reports**

1. More Information

To please update with the following text:

A program of public health surveillance is being implemented in 58 outpatient clinics in Madagascar, in partnership with WHO and Ministry of Health. The project introduces case-based, integrated disease surveillance of priority diseases, conditions and events.

The clinician uses the system within the consultation, which introduces clinical-decision support as well as best practice prescribing guidance and and real-time reporting of information. Information is made available within one hour via an online framework with automated generation of SMS and email alerts and support for mapping and reporting.

**Comment by mrjb** [comment]
Is this a higher or lower priority than the Malaria report? I can make this the next job on my list if you want...

**Comment by mrjb** [comment]
Does it make sense to include completeness indicator in all country versions of communicable disease profile report?

**Comment by mrjb** [comment]
@johnhaskew Just a nudge regarding my completeness query above. I don't really understand what value you want this to be...

**Comment by johnhaskew** [comment]
So I am passing this to @Gulfa who is thinking about how to approach the completeness issue. We currently calculate this indicator in the dashboard but realise it is in a process of change. 

The current idea is to calculate % completeness over the previous two weeks. So in the report, we could just use the previous two weeks prior to the start date of the report for example. Or could we calculate for the period of the report itself?

There is no problem to omit for now if easiest and to include when completeness is fixed properly. Gunnar?

**Comment by Gulfa** [comment]
So I think I have more or less figured out how to calculate the completeness. There are a few details we need to discuss before I can finish the new way of calculating it. 

I suggest we omit this for now and then I will finialise the new and improved method for calculating completeness as soon as possible.

**Comment by johnhaskew** [comment]
Thank you so much for making the above corrections.

Some other comments if I may:
1. Some results in the Epidemiological Monitoring Report are listed as NaN or undefined? Can we just list as 0?

Also:
1. French naming of report in the drop-down list is not correct?
2. Translation within reports is not applied fully?

Is this an issue of not completely translating all words yet? I will make a comment in the translation issue regarding how best I can sort out remaining translations...

**Comment by mrjb** [comment]
I believe these issues are all sorted and will be included in the next deployment.
