### ISSUE TITLE
Madagascar Email Reports

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#108]
Dear Jyri, Jonathan - please find attached the three reports to be emailed each week for Madagascar:
1. Communicable Disease Profile
2. Weekly Epidemiological Report 
3. Malaria Surveillance Report

I attach english and french translations. If only one is possible, please use the French.

Please let me know if you need any further information and many thanks.

[Epi Report FR.docx](https://github.com/meerkat-code/meerkat_frontend/files/325095/Epi.Report.FR.docx)
[Epi Report EN.docx](https://github.com/meerkat-code/meerkat_frontend/files/325100/Epi.Report.EN.docx)
[Malaria Report FR.docx](https://github.com/meerkat-code/meerkat_frontend/files/325097/Malaria.Report.FR.docx)
[CD Report FR.docx](https://github.com/meerkat-code/meerkat_frontend/files/325098/CD.Report.FR.docx)
[CD Report EN.docx](https://github.com/meerkat-code/meerkat_frontend/files/325099/CD.Report.EN.docx)
[Malaria Report EN.docx](https://github.com/meerkat-code/meerkat_frontend/files/325096/Malaria.Report.EN.docx)

**Comment by mrjb** [comment]
The Malaria Data can be found as follows:
- **Consultations:** malaria_situation.mls_1
- **Health Facilities/Reporting Sites:** email.clinics
- **Fever Cases:** malaria_situation.mls_2
- **RDT Tests:** malaria_situation.mls_3
- **Simple Malaria:** malaria_situation.mls_12
- **Severe Malaria:** malaria_situation.mls_23
- **Malaria Deaths:** malaria_situation.mls_34
- **ACT:** malaria_situation.mls_45

The CD Report data can be found as follows:
- **Reporting Sites/Consultations/Cases:** email.clinics/consultations/cases
- **% Female:** percent_cases_female
- **% under five:** percent_cases_lt_5yo
- The other percentages are the indicators: public_health_indicators

Epi monitoring should be sorted?

**Comment by mrjb** [comment]
How about the API url /api/reports/cd_public_health_mad/1

**Comment by johnhaskew** [comment]
Could we please also include a CERF email report also. Exactly the same as CD profile except with the title change (please see attached).

Is it possible to limit this report only for Androy region (not the whole country). This is where the CERF is being implemented.

[CERF Report EN.docx](https://github.com/meerkat-code/meerkat_frontend/files/335074/CERF.Report.EN.docx)
[CERF Report FR.docx](https://github.com/meerkat-code/meerkat_frontend/files/335075/CERF.Report.FR.docx)

**Comment by jsoppela** [comment]
Malaria report, Epi report and CD reports are now done in html. The remaining tasks are:
- text-only reports
- translation to French or plain hardcoding the text in French
- adding CERF report

**Comment by jsoppela** [comment]
Can't get apostrophes to work and requiring translated disease list for CD report. @mrjb, could you help out with these? The French reports are ready for testing via Hermes distribution.
