### ISSUE TITLE
Updated Madagascar codes file

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#110]
@Gulfa - I am making an issue of this just so it doesn’t get lost.

1. MOH asked to separate what is suspected cholera and what is suspected acute watery diarrhoea and we have now updated the data collection forms accordingly. This now means the old AWD was labelled with icd_code A00 which is actually for cholera. 

Could we please therefore change all icd_code of A00 in the database to A09.0?

2. I attach the updated codes file which reflects these new definitions. Please use this file and not that sent earlier - we have not made cholera an alert in case any old forms are still submitting A00 for diarrhoea.

Many thanks.

[mad_codes.xlsx](https://github.com/meerkat-code/meerkat_frontend/files/335187/mad_codes.xlsx)

**Comment by mrjb** [comment]
Hi John, I don't entirely follow this.  Change all A00 for A09.0, seems to make sense.  But then there are plenty of A00's still referred to in the example codes file you have shared. So perhaps I've missed something?

**Comment by Gulfa** [comment]
They can stil submitt new cases with A00, but we assume all current cases of A00 are actually A09.0.

**Comment by mrjb** [comment]
Ah right with you.

**Comment by Gulfa** [comment]
@johnhaskew: Can you please send a new version of the mad codes file where your changes are added to the latest version of the codes file. We need a better way for you to send codes file changes.
