### ISSUE TITLE
Translation key not found - Mapbox integration

### ISSUE THREAD

**Issue by jonathansberry** [meerkat-code/meerkat_frontend#112]
Something really ugly happens in the browser console when moving the mouse over the mapbox maps.  An error message is repeated over and over again, presumable on some hover/mousein/mouseout event... `Error: No translation key found.`

**Comment by Gulfa** [comment]
Is this still an issue?

**Comment by jonathansberry** [comment]
No actually I fixed this issue as part of the afro report prep.
