### ISSUE TITLE
Some bugs :)

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#114]
Some annoying small bugs :)

1. In Demographics tab:
-Week 26 in the tables is not translated into French - **not updated yet**
-the order of age group is incorrect e.g. <5 should be listed first  **not updated yet**

1. We need to change _Message 260_ in the messages.po from Acute Watery Diarrhoea to Acute Diarrhoea

2. The following are not yet included in translation (default settings for report periodicity in the report menu):
-_last epi-week_, should be _dernière semaine épidémiologique_
-_current year_, should be _année actuelle_

3. _Reports_ menu item has the following english text which should be removed:
-_Here you can download summary reports drawn from the epidiemological data. still in reports section in english._

4. Selection of reports in the _Notifications tab_ seems to have a mix of english and french still and the reports are not updated. If we can please update.

5. The following translation bugs are found in the _Central Emergency Response Fund (CERF) Bulletin_
and _Profil de la Maladie Transmissible_ reports:
-_Key Findings_ heading is not translated into french
-The indicators below are not translated into french:
--Alerts generated  **not updated yet**
--Alerts investigated  **not updated yet**
-The Information Box text at the bottom is in english and not in french

6. The following translation bugs are found in the _Rapport de Surveillance Épidémiologique Hebdomadaire_
-Nombre de décès maternelss should be Nombre de décès maternels
-Tétanos néo natal is listed twice in second table entitled "Maladies objet de programme d’élimination ou d’éradication". _Suspicion cas de rougeole_ is missing (please refer to the original translation)
-Undefined, NaN and NA is still listed in the report if we can please just listed as 0.

7. The following translation bugs are found in the _Rapport de Maladies Transmissibles_
-The information text below each case is still in english e.g.
-_There were 0 new confirmed cases and 0 new suspected cases of Acute Flaccid Paralysis between 01 janvier 2016 and 04 juillet 2016._

8. The latest reports don’t seem to be displaying in the notification selection menu?

9. Please change the order of logos - so MOH first, then WHO on the splash page (both in the map and in the bottom of the page) as well as in the footers of the technical site etc. Please also change the order in which the names are listed in the footer.
**The order of list of partners and logos needs to be MOH, DVSSE, WHO (WHO always last), same in Jordan and Djibouti. The order of logos in Reports is not changed yet.**

10. Footer bar: The sentence: _For more information, please e-mail:_ is not translated to french.

11. In Explore - 
Governorates should be renamed Region
Directorates to District 
**Sorry - if we can please rename to the plural - Districts
Also to rename Cliniques as Sites de surveillance**

12. Please remove _Map View_ from the dashboard which is not really informative. We know we can improve mapping in due course.

**Comment by Gulfa** [comment]
Will sort this tomorrow.

**Comment by johnhaskew** [comment]
@Gulfa  - i just updated the comments above to note where comments are not yet updated.

**Comment by johnhaskew** [comment]
Thanks so much @Gulfa
