### ISSUE TITLE
Jordan PIP Reports

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#119]
I note that the PIP report has some bugs in it still:
https://jordan.emro.info/en/reports/pip/1/2016-07-26T00:00:00.000Z/2016-01-01T00:00:00.000Z/

date range is not displayed correctly:
represents cumulative cases reported from 3 sentinel sites between %-1 %B %2016 and %-26 %B 

and King Abdullah Moa’asses SARI Sentinel Site is not displaying correctly

**Comment by mrjb** [comment]
Hi John,  Will sort this out now before I redeploy.  Can you just explain what you mean by: "king Abdullah Moa’asses SARI Sentinel Site is not displaying correctly" This report was Gunnar's creation so I'm not fully up to speed with what we're expecting it to show.

**Comment by mrjb** [comment]
I "think" that the "King Abdullah Moa’asses SARI Sentinel Site" is not showing on the map because we don't currently have a longitude and latitude value stored for it in the Locations data.

**Comment by johnhaskew** [comment]
Hi Jonathan - so my comment related to the name being spelled as:
it currently shows as King Abdullah Moa&#39;asses SARI Sentinel Site

with apostrophe not formatted correctly. But yes you are right it is not showing the map also. I will include a GPS now so it can be corrected in this next commit. Many thanks
