### ISSUE TITLE
Activation of SMS messaging in Jordan

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#120]
Please can we active SMS messaging in Jordan. It seems no alerts are being sent by SMS.

**Comment by johnhaskew** [comment]
Yes emails are sent (although we still have the issue of sending to MOH addresses) but no SMS is being received.

Just also to say when entering the SMS confirmation code on the registration page, the most intuitive button to click that is located below the text box is to resend the code, not to submit. Perhaps we could re-align the submit and resend buttons so submit is directly below the box and resend is to the right side?

**Comment by mrjb** [comment]
I have changed the from address of the email field to notifications@emro.info. The change will be included in the next deployment. This should mean folk can verify their accounts properly.  As far as I am aware SMS messaging is functioning fine for the jordan deployment. So I will close this issue for now.
