### ISSUE TITLE
General Technical Site debugging

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#121]
**Demographics**
- Please allow comma separation of thousands in the total row of tables

**Alerts** 
- Please relabel all counts in the database:
	of A82 to T14.1
 	of A80 to A80.10

**Health Services**
- Please remove this tab for now

**Map View** 
- Please remove this tab for now

**Comment by mrjb** [comment]
@mixmixmix Comma separation of table values probably needs to be built into your work with bootstrap tables. There is already a function for doing this in `src/js/technical/misc.js` called `format(number)` it just needs to be called when inserting the data into the bootstrap table.

**Comment by mrjb** [comment]
I have removed the Health services and Map View.

**Comment by mrjb** [comment]
@johnhaskew By relabel counts of A82 and A80, do you jsut mean replace all references to them in the jordan codes file?

**Comment by johnhaskew** [comment]
Thanks Jonathan. I mean to recode all cases of A82 (which is rabies) to be renamed as T14.1 (which is animal bite) because it is an error in form entry coding on our part.

The same for A80 (polio) which is not polio and should be renamed to A80.10 (which is AFP).

Many thanks.

**Comment by mrjb** [comment]
So we need to fix this in the data already submitted? I've actually never done that, and don't know how.  I know Gunnar says it's not an easy process and means getting your fingers dirty with the raw data in aggregate. This is in part why we want to build the data management module. How urgent is this?

**Comment by johnhaskew** [comment]
Ok no problem - hopefully Gunnar can help with this. We would need to change by 9 August though before these meetings.

**Comment by mrjb** [comment]
I believe Gunnar has made the database changes, meaning this issue is just waiting on the work from @mixmixmix .
