### ISSUE TITLE
PIP bugs

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#123]
**PIP Report**
- Please reduce the font size of the Viral Aetiologies subheader in the key findings box
- Please verify and update the status of laboratory results in the epi curve report according to the below:

pcr./flu_b_pcr = negative and pcr./h1n1_pcr = positive: Status = **H1N1** (colour = red)
pcr./flu_b_pcr = negative and pcr./h3_pcr = positive: Status = **H3** (colour = yellow)
pcr./flu_b_pcr = negative and pcr./flu_b_pcr = positive: Status = **B** (colour = blue)
pcr./flu_b_pcr = positive and pcr./flu_a_pcr = positive: Status = **Mixed** (colour = grey)

**PIP Tab in Technical Site**

- Please verify and update the status in the alerts line list according to the above, so they will read: H1N1, H3, B or Mixed.

**PIP Download**

- Please include Laboratory data in the Download function

**Comment by mrjb** [comment]
Hi John,  types are currently determined according to the following columns and conditions...
```"type": {
                "Influenza A": {
                    "column": "pcr./flu_a_pcr",
                    "condition": "positive"
                },
                "H1": {
                    "column": "pcr./h1_pcr",
                    "condition": "positive"
                },
                "H3": {
                    "column": "pcr./h3_pcr",
                    "condition": "positive"
                },
                "H1N1": {
                    "column": "pcr./h1n1_pcr",
                    "condition": "positive"
                },
                "Influenza B": {
                    "column": "pcr./flu_b_pcr",
                    "condition": "positive"
                }
            } ```

Can you confirm that status = *A* should be: 
pcr./flu_b_pcr = negative and pcr./flu_a_pcr = positive: Status = *A* (colour = *???*)

Also you say:
pcr./flu_b_pcr = negative and pcr./flu_b_pcr = positive: Status = *B* (colour = blue)

But I'm assuming this is an error because the value can be both positive and negative at the same time surely? 

At the moment, I don't think we have the code to define link types based upon two different conditions, but I'm sure I can figure out the code needed to make that happen.

**Comment by johnhaskew** [comment]
Thanks Jonathan - so we can remove Influenza A. Infact H1N1 and H3 are both subtypes of A and there is no A on its own.

For Influenza B, yes it was a mistake sorry:
pcr./flu_b_pcr = positive and pcr./flu_a_pcr = negative: Status = B (colour = blue)

**Comment by mrjb** [comment]
By "include laboratory data in the download function" do you mean the "download raw data" part of the "download" page. I notice that "labs" is currently broken.

**Comment by johnhaskew** [comment]
so that the lab results are included in the prepared "PIP" excel sheet that is downloaded by default (from the drop down list). what do you mean labs is broken?

**Comment by mrjb** [comment]
There's something strange happening when selectding labs from the download raw data form. it's not updating the fields properly. I'll make an issue for it, but presumably it isn't a priority at the moment...

I see, so maybe if I add a column "laboratory results" to be filled with the "H1N1", "H3", "B" or "Mixed" if confirmed and "suspected" if not?

**Comment by mrjb** [comment]
Can I just confirm that we are getting rid of H1 and just keeping H1N1 and H3?

**Comment by mrjb** [comment]
Everything apart from the download data update should now be deployed.  Have a glance over it and let me know if something isn't right.

**Comment by mrjb** [comment]
This should all be deployed now.
