### ISSUE TITLE
CD and NCD profile report  Public Health Indicators changes

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#132]
**NCD Profile**
To please replace **_Laboratory results recorded_** in the Public Health Indicators section with more specific indicators:
**Patient have smoking status recorded
Diabetes mellitus patients have HbA1C recorded
Hypertension patients have BP recorded**

To please replace **_Prescribing practice recorded_**  with a more specific indicator _**Availability of prescribed medicines**_ calculated as would be medicine_available1 = yes / medicine_name1 (any entered)

**CD Profile**
To please remove **_Laboratory results recorded_** indicator for now

To please replace **_Prescribing practice recorded_**  with a more specific indicator **Availability of prescribed medicines** calculated as would be medicine_available1 = yes / medicine_name1 (any entered)

**Comment by Gulfa** [comment]
What french translation shall I use for "Availability of prescribed medicines" ?
