### ISSUE TITLE
Completeness Tab Alterations

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#145]
**To please relabel the bottom left table of the Completeness tab**, called Clinics not reporting:

Clinics not reporting / Sites de surveillance ne déclarant pas -> Reporting sites never reported / Sites de surveillance jamais signalés

**And to also add a yearly column** to both the top left table and the bottom right table.

**Comment by jonathansberry** [comment]
@Gulfa Is the yearly completeness data already spewed out by the api? Or will this require some backend development.  I can't obviously see yearly data from inspecting the json dump.

**Comment by mixmixmix** [comment]
I think it will be much easier and elegant to modify backend. I thought I can do it but I'm a bit confused with the indexing:
```
last_two_weeks = completeness.index[-1:]
```
@Gulfa, could explain how it works, or just how to modify the following line to get yearly score?
```
 score.loc[location] = completeness[last_two_weeks].mean() / number_per_week * 100
```
Alternatively I'm happy to work out with timeliness in frontend. Let me know.

**Comment by Gulfa** [comment]
So I agree that it is better to add the yearly data calculated from the backend. 
It should essentially be to do this: 

yearly_score[location] = location_completeness_per_week.mean() / number_per_week * 100

I do apologies about that indexing. In the beginning we actually used the last two weeks for the completeness score, but we changed it to just one week. Therefore the variable name and the index does not match up very well. 

Great if you could edit the API to sort this out.

**Comment by mixmixmix** [comment]
I added yearly completeness columns. "Yearly completeness" is a very long phrase so I shortened it to "Yearly", but maybe someone has a better idea for a name. All ready in frontend branch [iss145](https://github.com/meerkat-code/meerkat_frontend/tree/iss145) and using API [yearly_score](https://github.com/meerkat-code/meerkat_api/tree/yearly_score) (@gulfa, you can see my changes in API to second check that I calculate numbers correctly). 
![screenshot from 2016-11-08 18-32-40](https://cloud.githubusercontent.com/assets/9990867/20111874/d9ddc252-a5e1-11e6-8455-5135fc3bb462.png)

**Comment by jonathansberry** [comment]
Looks great! :-) I think the box title probably makes it clear that we're tabulating completeness.  I think I might just change the three column headings to "Location", "[This ]Week" and "[This ]Year" respectively.  You could probably even drop the word "This", for the compressed table.

**Comment by mixmixmix** [comment]
Thanks for feedback @jonathansberry. It's done now, ready to merge.

**Comment by jonathansberry** [comment]
This great Mix.  Thanks!  It all seems to have merged into master nicely.  We'll close this for now and await John's feedback as we approach the end of the milestone.
