### ISSUE TITLE
Configurable Completeness Denominator

### ISSUE THREAD

**Issue by Gulfa** [meerkat-code/meerkat_frontend#147]
For completeness we are currently hard coding the value of the denominator for the completeness calculation. We should set this up so that we can have different values for different tabs and that these values can be configurable using the standard config files.

**Comment by Gulfa** [comment]
The function that calculates the week days not reported also can take the weekend days as arguments. We need to be able to specify these also in the config files.

**Comment by mixmixmix** [comment]
The denominator is ready now. Change to weekend days needs to be done in API as far as I'm concerned, I will look at it now.

**Comment by mixmixmix** [comment]
in progress.

**Comment by mixmixmix** [comment]
PRs for this issues are ready for merging:

- https://github.com/meerkat-code/meerkat_frontend/pull/190
- https://github.com/meerkat-code/meerkat_jordan/pull/7
- https://github.com/meerkat-code/meerkat_mad/pull/7
- https://github.com/meerkat-code/meerkat_api/pull/28

For Madagascar and Jordan I've put default weekend values as [5,6], I don't know if those are correct though!

**Comment by mixmixmix** [comment]
All is merged.
