### ISSUE TITLE
PDF Report Maps

### ISSUE THREAD

**Issue by jonathansberry** [meerkat-code/meerkat_frontend#148]
Establish a means of generating maps for reports showing data from the system.

First and foremost we could do with being able to show incidence of Malaria per 100,000 population across Madagascar.

We're looking for something a little like the "Map" tab in the dashboard.

**Comment by jsoppela** [comment]
Docraptor api is now implemented in infrastructure and frontend branches issue148. However, enabling javascript will produce jQuery-related errors:

[docraptor_js_log.txt](https://github.com/meerkat-code/meerkat_frontend/files/608335/docraptor_js_log.txt)

**Comment by jonathansberry** [comment]
I believe that all pdf report maps should now be showing properly in master. Will close for now.
