### ISSUE TITLE
Backend for AFRO Weekly Bulletin

### ISSUE THREAD

**Issue by jonathansberry** [meerkat-code/meerkat_frontend#150]
To build an API call that serves all the necessary data for assembling the report outlined in this file:

[AFRO Weekly Bulletin Template.docx](https://github.com/meerkat-code/meerkat_frontend/files/563578/AFRO.Weekly.Bulletin.Template.docx)

**Comment by jonathansberry** [comment]
I've created a stub for this in the "afro-report" branch. It appears at `/reports/afro/<location>`.

**Comment by jonathansberry** [comment]
@jsoppela and I have created and started to populate this spreadsheet detailing how to calculate all the required values:
https://docs.google.com/spreadsheets/d/1ljnvcqMLDOLLVzkwaoLVu93eMlbKaeZ3bvfo2VPc9xk/edit?usp=sharing

**Comment by mixmixmix** [comment]
I've read through the report and have noticed following issues to investigate:

1. Wrong values for fever highlights

> A total of 711712581 fever cases were reported, 2216 (0.0%) tested and 365 (0.0%) positive 

2. Measles cases over and under 5 always equal
3. Summary of priority diseases: cummulative deaths can be more than cummulative cases: 42,   10 , giving `CFR = 420%` for `Other/Alert`

**Comment by mixmixmix** [comment]
Remarks mentioned earlier by Jyri:
> In the priority disease tables, the disease cases broken down by region do not add up to the total disease cases

We are not reporting total for the country, but seems that something isn't right indeed. Here are two API calls we use and their results:
```
          priority_disease_cases = map_variable( 
            disease,
            start_date, 
            end_date_limit, 
            location, 
            conn,
            group_by="region"           
          )   
          priority_disease_cases_total = map_variable( 
            disease,
            start_date, 
            end_date_limit, 
            location, 
            conn,
            group_by="country"           
          )          
```
resulting in
```
priority_disease_cases for cmd_1
{2: {'value': 55, 'geolocation': ['-19.26667', '48.3'], 'region': 'Alaotra-Mangoro'}, 3: {'value': 7, 'geolocation': ['-18.9053', '47.367'], 'region': 'Analamanga'}, 4: {'value': 4, 'geolocation': ['-19.276395', '46.2932'], 'region': 'Bongolava'}, 5: {'value': 38, 'geolocation': ['-25.5657', '45.528'], 'region': 'Androy'}, 7: {'value': 9, 'geolocation': ['-17.1087', '49.808'], 'region': 'Analanjirofo'}, 8: {'value': 24, 'geolocation': ['-23.1704', '47.6463'], 'region': 'Atsimo-Atsinana'}, 11: {'value': 1, 'geolocation': ['-14.99908', '50.1393'], 'region': 'Sava'}, 12: {'value': 40, 'geolocation': ['-22.415293', '47.8657'], 'region': 'Vatovavy Fitovinany'}, 13: {'value': 6, 'geolocation': ['-25.052375', '44.549963'], 'region': 'Atsimo Andrefana'}}
priority_disease_cases_total
{1: {'value': 38, 'geolocation': ['-25.5657', '45.528'], 'country': 'Madagascar'}}
```

**Comment by jonathansberry** [comment]
With regard to Fever - there is a data error that @gulfa is fixing, we won't need to worry about percentages once the fix has been put in place.

**Comment by jsoppela** [comment]
The mortality figures for tables 1 and 2 are now calculated using mapping dictionaries that map a disease case variable into a disease mortality variable. These mapping variables are used to map mortality variables in variable category 'deaths' correctly. Mortality variables mor_28 and mor_29 for disease variables cmd_3 and cmd_14 still need to be added to the coding file.

**Comment by jonathansberry** [comment]
Gunnar has reviewed this today.  We're at a point where we can probably show John our work! So I will close this for now (it feels good) and we can reopen if necessary later.
