### ISSUE TITLE
Jordan Mental Health Report

### ISSUE THREAD

**Issue by mixmixmix** [meerkat-code/meerkat_frontend#152]
Current version is on a branch `mh_report` in `meerkat_[jordan|api|frontend]`.
It requires following work:

- gender breakdown
- tests
- sorting of indexes

## Here is a further specification of the report:
New codes introducedto deal with visit types :
`gen_3/gen_4` - gender visit
`nat_{9 .. 16}` - visit nationality
`age_{47 .. 55}` - visit age, same age brackets as NCD
`prc_{8 .. 13}` - visit diseases type

**Comment by mixmixmix** [comment]
### Relevant codes:
- `vis_1,vis_2,vis_3` - visit type (New, Return, Referral)
- `visit_gen_1/visit_gen_4` - visit gender / case gender
- `visit_nat_{1 .. 8}` - visit nationality / case nationality
- `visit_age_{20 .. 28}` or `age_{20 .. 28}`  - visit age / case age
- `visit_prc_3` and `prc_3` - Mental health visit, Mental health case

### Remarks:
- Categories (nationality and age) shall always be breaked up by gender


### Tables:

#### Visit based:
1. *visit type / nationality* Make extension to query_category to use it with `only_variable=pcr_6`:  `visit type`, `nationality`.
2. *visit type / age* Same as 1.

#### Case based: 
3. *governate / nationality* 
4. *governate / age* 
5. *diseases / nat*: 
6. *disease / age*:

**Comment by mixmixmix** [comment]
the api branch is issue152-rebranch
freontend and  meerkat_jordan branch are issue152

**Comment by mixmixmix** [comment]
Required changes:
- Add breakdown by gender for each category
- fit the tables on the screen
- Change nationality list to: jordanian, refugee syrian, refugee other, palestynian, other. (new codes)
- Visit types: New, return, referral, admission, consulatation, other (ask John how it is coded)
- Add totals for each nationality

**Comment by jonathansberry** [comment]
Can you consolidate this issue with issue #260 Mix?

**Comment by mixmixmix** [comment]
How do I consolidate issues?

**Comment by jsoppela** [comment]
Visit types have been checked from John and the current list we have (new, return, referral) is correct

**Comment by mixmixmix** [comment]
Outstanding issues:

- [ ] Find out a bug in calculating totals over y axis (there is one, I promise)
- [ ] Adjust jinja template (possibly by normalising names of the axis to be always “x_category” and “y_category” instead of “nationalities” and “age_groups” and “name” and “type"
- [ ] change nationalities to the new codes in the API

**Comment by Gulfa** [comment]
Will close this issue as the draft was sent. Can reopen a new issue if we get feedback.

**Comment by mixmixmix** [comment]
0. Changing layout
[Uploading changes-to-mh2.docx…]()

1. Separate disease related tables for mhGAP and ICD-10 classification
2. Breakdown by Service provider: 
MOH, RMS, Universities, NGOs, UNRWA 
3. Breakdown by result of visit:
Therapy, Consultation, Admission, Referral,End treatment
