### ISSUE TITLE
Table of vials used in Vaccination Report

### ISSUE THREAD

**Issue by Gulfa** [meerkat-code/meerkat_frontend#154]
We want to add a table to the vaccination report which displays the number of vials used. 

This will essentially be the number of vaccinations divided by the number of doses per vial. Will attach this information as soon as we have it. There will be a different number for each type of vaccination.

**Comment by Gulfa** [comment]
We can use the current data to calculated the number of vials used: 


Type	doses/vials
BCG	20
DTCHepHib	10
PCV10	2
ROTARIX	1
VPO	20
VPI	5
VAR	10
VAT	20

**Comment by mixmixmix** [comment]
Ready for merge.
