### ISSUE TITLE
Change age categories for Malaria report

### ISSUE THREAD

**Issue by Gulfa** [meerkat-code/meerkat_frontend#161]
Add 0-11mois / 12-59mois instead of <5ans and add the following to the table:
	 	 	 	 	 	 	 
Nombre de RDT négatif	 	 	 	 	 	 	 	 	 	 
Nombre de RDT positif	 	 	 	 	 	 	 	 	 	 
Nombre de RDT non fait

**Comment by jsoppela** [comment]
The changes have now been made, but there are a few remaining issues:

- The RDT numbers do not make sense to me. Are they correct?
- RDT numbers are in the table twice. Is this as intended?

A screenshot:
![malaria_report_issue161](https://cloud.githubusercontent.com/assets/9406814/21687495/607e7b2e-d361-11e6-9411-35d32db20c80.jpg)

**Comment by johnhaskew** [comment]
Hi Jyri - number of RDT positif (positive) equals the number of palu simply, grave (serious) and inconvnu (unknown) which is good.

The number RDT negative (negative) and non fait (Not done) should equal RDT effectues (Done) (which is 2,557) minus RDT positive (512) however. Clearly this is not right as they are both 0.

Otherwise all looks ok.

**Comment by jsoppela** [comment]
Thanks for the comments, I was suspecting something is fishy with the numbers. I'll investigate why they look like they do.

**Comment by jsoppela** [comment]
It appears that the numbers that are circled red in the attached screen shot are always zero. There are no cases where a confirmed malaria case would have an RDT test negative or Not done. Could these columns be removed?
![malaria_report_issue161_2](https://cloud.githubusercontent.com/assets/9406814/21806415/0616319e-d731-11e6-847e-97371c8f57be.jpg)

**Comment by jsoppela** [comment]
According to discussion with @johnhaskew, the RDT columns "Negative" and "Not done" have been removed and the rows "Number of negative RDT tests" and "Number of RDT tests not done" are calculated using data from rows "Number of fever cases", "Number of RDT tests performed" and "Number of positive RDT tests". 

This is how the report looks at the moment:
![malaria_report_issue161_3](https://cloud.githubusercontent.com/assets/9406814/21812728/c81387fa-d74b-11e6-9aa6-e7aad72d20a1.jpg)

**Comment by johnhaskew** [comment]
This is great Jyri thank you
