### ISSUE TITLE
Unification of coding files

### ISSUE THREAD

**Issue by jsoppela** [meerkat-code/meerkat_frontend#204]
The coding files that define how the Abacus variables are calculated from the ODK Aggregate raw data are currently country-specific. They do not share codes even though in reality the the countries share a large amount of variable codings. Unifying the coding will reduce redundant testing. In addition, breaking down the coding files into modules will reduce merge conflicts when doing parallel development.

**Comment by jsoppela** [comment]
Things to do:

- [ ] Edit import function to handle a list of coding files as a parameter
- [ ] Break down coding files for Demo
- [ ] Break down coding files for Jordan
- [ ] Break down coding files for Madagascar
- [ ] Break down coding files for RMS

**Comment by mixmixmix** [comment]
I suggest to break down coding files for Test as well (unless we will make test_codes the same as demo_codes)

**Comment by jonathansberry** [comment]
All priority issues have been moved to the private meerkat_issues repo.
