### ISSUE TITLE
CD Completeness/Timeliness 

### ISSUE THREAD

**Issue by jonathansberry** [meerkat-code/meerkat_frontend#212]
Respond to request from Dr Sami, "to remove background grey lines from the completeness / timeliness tabs". 

- [x] Gunnar to confirm that this is exactly what Dr Sami wants.
- [ ] Mix to implement changes

**Comment by mixmixmix** [comment]
Adding a box to enable/disable the feature.

**Comment by mixmixmix** [comment]
Lines removed in https://github.com/meerkat-code/meerkat_frontend/tree/iss212

**Comment by jonathansberry** [comment]
@mixmixmix You asked about the user interface.  As a first suggestion how about [this?](https://www.dropbox.com/s/9msisg9mvx6shfw/compare-locations.png?dl=0)
The bootstrap glypicon I've use is "glyphicon glyphicon-random" which seemed appropriate for showing multiple lines.  However, I could also be easily persuaded to use "plus" and "minus" icons instead.  The tool tip then further explains what the button does.  "Compare locations" seemed to be a pretty clear and crisp description of what the extra lines are there for - again if you think of a better phrase then that's fine.
