### ISSUE TITLE
Download Completeness/Timeliness Data

### ISSUE THREAD

**Issue by jonathansberry** [meerkat-code/meerkat_frontend#213]
There needs to be a means of downloading completeness and timeliness data in spreadsheet format.  

This could be through the download data form, or could be even more easily done by adding an "excel" link to the table in the dashboard. 

- [x] Gunnar to confirm the required structure for the downloaded data.
- [ ] Implement the changes.

**Comment by mixmixmix** [comment]
Is there a way I can help with that? I'm quite keen to learn how we are preparing offline data for download.

**Comment by jonathansberry** [comment]
This just needs an excel link in the dashboard tabs, such as we have in the demographics tab for each table.  "Hopefully" dead easy. You happy to look at it Mix and let me know if you come across any big problems?

**Comment by jonathansberry** [comment]
Ok. I'm on this now.  Should have it done this afternoon.
