### ISSUE TITLE
Downloaded Data Dates Format

### ISSUE THREAD

**Issue by jonathansberry** [meerkat-code/meerkat_frontend#215]
"To format the date in download that is able to be formatted automatically and used"
"To include year, month, day columns for the visit in downloaded data"

- [x] Gunnar to find out what form the dates are wanted in exactly.
- [x] Format the dates.
- [x] Add a day column to the downloaded data

**Comment by Gulfa** [comment]
We can just use the DD/MM/YYYY format.
