### ISSUE TITLE
NCD Downloaded Data

### ISSUE THREAD

**Issue by jonathansberry** [meerkat-code/meerkat_frontend#216]
Feature enhancements for the NCD downloadable data set.

 - [x] Gunnar/John to provide hard data definition for each new column
 - [x] Add columns to downloaded data: diabetes type, and hypertension.
 - [ ] Add columns to downloaded data: patient symptoms, risk factor, complications, co-morbidities
 - [ ] To include BMI results in download to one decimal place only

**Comment by Gulfa** [comment]
Symptoms: symptoms ( translated via jor_sympt.csv)
Risk factors: risk (translated via jor_risk.csv)
Complications: ncd_complications
Comorbidity: comorbididty

So symptoms and risks needs to be translated using the attached files. Essentially the symptoms variable in raw data has a code that corresponds to sympt_code in jor_sympt.csv. We want the downloaded column to show the jor_sympt column that corresponds to the sympt_code in the jor_sympt file. And the same for the risk factors. 




[files.zip](https://github.com/meerkat-code/meerkat_frontend/files/726147/files.zip)

**Comment by jonathansberry** [comment]
@johnhaskew Can each record have multiple Symptom codes and multiple risk factors?  If so are they provided as a comma separated list, or are the divided up in some other way?

**Comment by jonathansberry** [comment]
@gunnar / @johnhaskew Any strong opinions about where these fields are ordered in the downloaded data set?
