### ISSUE TITLE
NCD New and Return Visit Reports

### ISSUE THREAD

**Issue by jonathansberry** [meerkat-code/meerkat_frontend#218]
"To update NCD Reports as new / return visits."

**Comment by jsoppela** [comment]
![initial_visits](https://cloud.githubusercontent.com/assets/9406814/22313265/e46e4674-e353-11e6-900a-ac7a495750b1.jpg)
![return_visits](https://cloud.githubusercontent.com/assets/9406814/22313267/e780afe6-e353-11e6-8a99-276403ad6321.jpg)
