### ISSUE TITLE
Exception handling in reports API

### ISSUE THREAD

**Issue by jsoppela** [meerkat-code/meerkat_frontend#232]
Report APIs defined in meerkat_api/meerkat_api/resources/reports.py will crash with KeyErrors if they do not get the expected data structures from the database. Exception handling should be added to keep the API crashing even when there are issues with the DB.

**Comment by mixmixmix** [comment]
Can we add exception handling on the level of extracting data from database instead of report creating level?

**Comment by jonathansberry** [comment]
All priority issues have been moved to the private meerkat_issues repo.
