### ISSUE TITLE
Check email reports

### ISSUE THREAD

**Issue by Gulfa** [meerkat-code/meerkat_frontend#244]
At least the malaria email report has a mistake in the number of cases treated by ACT. This should not be 0.

**Comment by Gulfa** [comment]
I think I have fixed the malaria email. There were some code mismatches. Can we please go through and double check all the emails.

**Comment by jsoppela** [comment]
Checklist for the emails:
- [ ] CD Public Health Profile
- [ ] CERF
- [ ] EPI monitoring
- [ ] Malaria
- [ ] NCD Report New Visits
- [ ] NCD Report Return VIsits
- [ ] PIP
- [ ] Public Health Profile
