### ISSUE TITLE
Indicators tab

### ISSUE THREAD

**Issue by mixmixmix** [meerkat-code/meerkat_frontend#246]
Under developement in branch `indicators` of api, infrastructure, jordan and frontend.

**Comment by mixmixmix** [comment]
### Outstanding issues (in order of importance/difficulty):
1. https://github.com/meerkat-code/meerkat_api/blob/indicators/meerkat_api/resources/indicators.py#L106, `series_to_json_dict()` does not convert `numpy.int64` into `int`. As a hack I convert all values to `int`, even if they are fractions. 
2. I'm not sure if I limit to restricted variables correctly. (https://github.com/meerkat-code/meerkat_api/blob/indicators/meerkat_api/resources/indicators.py#L53)
3. Code does not handle a case for one-week-old data.
4. There is no start_date/end_date handling

@Gulfa, could you advise me on **2**, and weather I should do **1** or leave it for you?

**Comment by jonathansberry** [comment]
Can we close this issue mix?

**Comment by mixmixmix** [comment]
Not really. We need to address outstanding issues. We can either do it now or come back to it once we have more indicators specified.
