### ISSUE TITLE
Foreigner Screening

### ISSUE THREAD

**Issue by jonathansberry** [meerkat-code/meerkat_frontend#261]
Foreigner screening tab: 
- [x] Update
- [x] Report

**Comment by jsoppela** [comment]
[foreigner form screening.docx](https://github.com/meerkat-code/meerkat_frontend/files/827942/foreigner.form.screening.docx)

**Comment by jsoppela** [comment]
Attached the spec

**Comment by mixmixmix** [comment]
I understand two reports:
- [ ] Report for TB screening program
- [ ] Report for Migrant Health (HIV& HBs) screening program

However, what is this Health Certificate? It requires phone number and surety information which is personal data we cannot handle.

**Comment by Gulfa** [comment]
We do not need to worry about the health certificate. I agree that it looks like two reports, but they should be quite simple.

**Comment by Gulfa** [comment]
For this milestone we will focus on getting the form ready.

**Comment by Gulfa** [comment]
Will close this issue for this milestone. We might have to do some more work on FS in the future.
