### ISSUE TITLE
Download data progress bar

### ISSUE THREAD

**Issue by jonathansberry** [meerkat-code/meerkat_frontend#263]
A progress bar giving feedback on the download data process should be added to the Frontend.  The bar should also indicate when an error has occurred in the download data process.

**Comment by Gulfa** [comment]
In download-data branch the status in the database should now show the fraction of number of rows finished / total_rows

**Comment by Gulfa** [comment]
Have a basic progress indicator ready for the "From Jordan" milestone. Will move this issue from the milestone.
