### ISSUE TITLE
Download Data

### ISSUE THREAD

**Issue by jonathansberry** [meerkat-code/meerkat_frontend#271]
Formatting of week and year in the download data.

**Comment by jonathansberry** [comment]
@gulfa - Can you expand on this?

**Comment by Gulfa** [comment]
This year since epi week 1 started on the 2nd of January. Cases from the 1st of January have epi_week 53 and year 2017. This makes little sense. Should either be epi_week 1 this year or epi_week 53 last year

**Comment by jonathansberry** [comment]
Ah sure... Thanks.

**Comment by jonathansberry** [comment]
This is done in the download-data branch. Will wiat to merge and deploy to development before closing.
