### ISSUE TITLE
Somalia Aggregate Server

### ISSUE THREAD

**Issue by jonathansberry** [meerkat-code/meerkat_frontend#272]
Set up a Somalia ODK Aggregate data server.

**Comment by Gulfa** [comment]
Would be great if we could get this done this week. I can help.

**Comment by jonathansberry** [comment]
Will do

**Comment by jonathansberry** [comment]
I have odk aggregate set up and working now. Presumably there are other things that need to happen?  e.g. data export scripts need to be loaded on to the server and set up?
