### ISSUE TITLE
Access to completeness locations broken in specific browser version

### ISSUE THREAD

**Issue by mixmixmix** [meerkat-code/meerkat_frontend#278]
Logging in with cd-clinic (jordan-clinic, jordan-cd): CD completeness tab is not able to load locations (says locations not available)
@jonathansberry

**Comment by jonathansberry** [comment]
I can't reproduce this issue.  Appears to work fine for me.  Let's talk.

**Comment by mixmixmix** [comment]
This issue seems to be related to specific version of Google Chrome on windows.

**Comment by mixmixmix** [comment]
It is not critical therefore

**Comment by jonathansberry** [comment]
I also can't replicate the issue in chrome and on windows... If you see the issue again, can you please get the js error from the console (it will be a js error) and try and work out what's happening. Then reopen the issue.
