### ISSUE TITLE
Unknown device model specific bug causes Collect to crash

### ISSUE THREAD

**Issue by jsoppela** [meerkat-code/meerkat_frontend#292]
MoH Jordan and RMS tablets have an issue with Collect which stops sending data altogether. The application crashes with message ""Unfortunately, APPNAME has stopped working" For now the issue has not been replicated on other device models. First reports of this issue are from 25/03/2017

It is possible that the issue is related to Android OS updates that have been distributed lately.

**Comment by jsoppela** [comment]
Findings and workaround candidates:
- Uninstalling and installing the app does not help
- A possible cause is system resources, purging app files needs to be tested as a possible workaround

**Comment by jsoppela** [comment]
Open questions:
- Only a single tablet model has been affected. What are the specifications of this model?
- What does the system resource view look like when the issue is met?

**Comment by Rania80** [comment]
the device in my hands now is TAB 2 A7-30HC from the same version that we are receiving problem from, the android version is 4.4.2
I am facing now problem with this device at all!! it was turned of when the problem started

**Comment by jsoppela** [comment]
> I am facing now problem with this device at all!! it was turned of when the problem started

Just for clarification, was the issue replicated on the device?

If not, can you instruct a user in the field to empty the odk folder, reinstall and see if it helps?

**Comment by Rania80** [comment]
no, it wasn't

I can't ask users for anything, this is the problem! devices are locked

**Comment by jsoppela** [comment]
There has to be a way for an administrator to get access to the devices as long as we don't have a central device control service such as G suite in use. Is any of the affected devices physically located near an IT administrator who has access the devices file browser or system resource view?

**Comment by Rania80** [comment]
it didn't show a prb, that's why i included version of android

**Comment by Rania80** [comment]
I've just got ur comment, yes there's an admin in every directorate, some of them are better than others in following our instructions
and I'm more an more encouraged to have a "management system" now! so pls let me know if u have any update on the offer for price, and if management system would be helpful in our case now

**Comment by jsoppela** [comment]
Will do, I got a response from TechSoup but they simply forwarded me to their local partners. Apparently they handle only US registered nonprofits themselves so I'll have to do some digging. I've opened an issue for updates about management system: https://github.com/meerkat-code/meerkat_frontend/issues/294

**Comment by Rania80** [comment]
the device are reporting "no more error"!

did you do any update and upload it to the server?

**Comment by jsoppela** [comment]
No updates have been done from our side since we still don't know the exact source of the issue. Did the contact person in directorate manage to catch any device logs of the error?

Do we still have non-functioning devices? If not, are we able to replicate the issue at all?

**Comment by Rania80** [comment]
no, he wasn't,, he tried to contact all the ones who reported the error on their devices and they said it's working fine now!
my phone stopped ringing and no one is reporting any problem, silence since yesterday afternoon

**Comment by jsoppela** [comment]
I'll close this GitHub issue later today if no further cases of devices not working are reported. In case you're requested to provide an explanation of what happened, the most probable cause was an automatic operating system or device firmware update which has now been fixed by Android dev team. Without logs of the error there's little we can do to investigate further since we haven't been able to replicate the issue on any other device.

**Comment by Rania80** [comment]
Ok, to hope we'll not face it again

**Comment by mixmixmix** [comment]
@jsoppela I don't think it is possible to do automatic updates of firmware or OS without connecting to WiFi (by default) which isn't possible with AppLock installed.

**Comment by jsoppela** [comment]
I'll close this issue since it is not relevant any more. We still don't know the root cause but another candidate for it would be the time zone change that happened on Sunday 26.3. The exact mechanism how this would have caused the issue would still be unknown as well as the reason why the issue solved itself.

**Comment by mixmixmix** [comment]
Until next year, little buggy bugs :)
