### ISSUE TITLE
Injuries

### ISSUE THREAD

**Issue by Rania80** [meerkat-code/meerkat_frontend#295]
Hi all,

We discussed the "Injury" in (Presenting Complaint) and that it might be counted from ICD-10 codes reflected from (animal bites)
We need to work on counter please and change how it reflects the data

**Comment by mixmixmix** [comment]
I believe this was meant to be posted in `jordan_feedback`. Can we re-open it there?

**Comment by Gulfa** [comment]
no point it should already be fixed
