### ISSUE TITLE
Downloading sheet from drive (urgent)

### ISSUE THREAD

**Issue by Rania80** [meerkat-code/meerkat_frontend#296]
I downloaded sheet from drive to check all entries manually as I am getting many complaints that there might be some mistakes (this is possible because I wasn't with one who distributed devices; this is logistics not IT task)
after downloading I discovered that the downloaded excel sheet doesn't match sheet on drive 100% accurate, and some cells are showing wrong data

**Comment by mixmixmix** [comment]
It is a known issue with excel that it doesn’t open csv data correctly. In some cases it interprets some numbers as formatted entires. For instance cell `29-03 will be **always** interpreted as 29th of March and if you then copy it to google drive it will say `29-03-2017`.
This file should really only be edited in google drive, or at least every time we should check that it is all correct.

**Comment by mixmixmix** [comment]
Is there any reason why this issue is not in `jordan_feedback`?

**Comment by jonathansberry** [comment]
All priority issues have been moved to the private meerkat_issues repo.
