### ISSUE TITLE
Frontend Translation

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#47]
Could we please look into ability to provide French and Arabic translation for the website and reports. 

Please let me know if we would use integration with Google Translate or equivalent or if you would require actual text, in which case I can provide...

**Comment by johnhaskew** [comment]
First off this is brilliant and completely seamless. Thank you again. It is completely transformative also here in Madagascar in the use of the system

Some comments:
1.	Please could you advise the best way to update or correct any translation issues
2.	As in the comment on the Malaria Report, translation doesn’t seem to be applied fully in some Reports? Only in some places?
3.	French naming of reports in the drop-down list is not correct

Please advise...

**Comment by Gulfa** [comment]
All translations are stored in the repositories as all other text. Translations are in the meerkat_frontend/translation/**/messages.po files. To changes any translation this file or the translation.csv file in the country repo has to be edited. 

2-3. @mrjb is fixing this. It just displays like that when the translation has not been done.

**Comment by mrjb** [comment]
It's already fixed and pushed. Will deploy again soon when I know we are ready.
