### ISSUE TITLE
Duplication of Daily Register or Case Report

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#58]
In the case of the Investigation Report, any report with most recent date will replace any previous report. Could we please do the same for the Daily Register and Case Report.

**Case Report:**
If any case report with same clinic, visit date, patient id, gender, age and icd_code is submitted the newest case report is registered only and previous is ignored.

**Daily Register:**
If any daily register with same clinic and visit date is submitted the newest case report is registered only and previous is ignored.

This can also solve the issue of entering incorrect information, e.g the large number of consultations found in one daily register. We can simply enter a new daily register with correct number for that day and it will replace and correct the old form.

**Comment by Gulfa** [comment]
This is a good idea, but technically not straight forward at all. Can look into this at a later stage.

**Comment by mrjb** [comment]
I will close this issue for now then.  It can be reopened when we are ready to look at it.
