### ISSUE TITLE
Weekly Email Templates

### ISSUE THREAD

**Issue by mrjb** [meerkat-code/meerkat_frontend#62]
The weekly email templates need to be updated to be flexible across different countries, to match up to the currently available reports, and to include an unsubscribe link.

**Comment by johnhaskew** [comment]
@jsoppela this functionality is a priority by the end of the month if possible. Gunnar and Jonathan are already committed - is it something you could take a look at?

**Comment by jsoppela** [comment]
I'll take a look. @mrjb, where are the weekly email templates stored in the version control tree?

**Comment by mrjb** [comment]
@jsoppela they are stored under meerkat_frontend/templates/reports. The email templates have "email" in the name. The only one I know of that was properly set up is the public health reports. I'd make a new branch to work on it. Crucially they include all the necessary CSS in the template and use appropriate html elements that can be interpreted by email clients. Hope that's helpful...
