### ISSUE TITLE
Descending order of tables

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#64]
To please show CD and NCD tab tables in descending order (so diseases with numbers are at the top).

Is it possible for filtering to be dynamic, so you can click on the column to choose ascending, descending order by name, number etc?

If not to simply, show descending by number of reported cases.

**Comment by Gulfa** [comment]
This is all possible. To do it in a nice way we will rewrite the table functions in the technical site to use bootstrap-tables. This will take a bit of time, but will happen.

**Comment by mixmixmix** [comment]
I'm almost finish with that on [this branch](https://github.com/meerkat-code/meerkat_frontend/tree/issue64). (I need to add Total and correct code tabulation)
@mrjb , could you take a look if it is what you expect?
Also there is a problem with sorting numbers bigger than 1000. Because they are represented with comma (for example. "1,674") bootstrap thinks it is a fraction. Is it a backend or a frontend issue? I'm willing to investigate but atm don't know how to see raw data.

**Comment by mrjb** [comment]
Hi Mix, Looking good! Thanks so much for making headway on this.  Was thinking about this...  It would be good if we could do our best to match the formatting of the tables to what they were previously: 
- Remove the outside border to the table
- Remove all vertical borders, leaving just the horizonal borders
- Ensure the table spans the full width of the container element (currently doesn't for CD tab). 
This will require delving into the SCSS which is probably a good thing to have a stab at if you're going to get stuck in to front end dev. Let me know if you have any questions. We then need to further add the following functionality:
- Create a button that highlights cells with a colour shade based upon the cells value.  This is already implemented in the Explore component: `explore/explore.js` src file. 
- Create a button that toggles between viewing the table with empty data rows (rows where all data values are 0) and without empty data rows (strip them from view).   This is also implemented in the explore functionality. 
- The html for the buttons I would imagine would be generated inside the table manage function.  They can just be made using the same bootstrap glyphicons used in the explore page and then right aligned directly above the table.  Perhaps make the buttons smaller than they are on the explore page. Or, if you have any good ideas about where we can cleanly place these buttons so as to not overcrowd the interface, let me know! 
  
Thanks again, and do get in touch if you have any questions/problems :-)

**Comment by mixmixmix** [comment]
I added functionality in commit 069316c.
Still to do:
- tidy up the code
- add colouring for numbers over 1000
- create buttons toggling the options (de-risked)

**Comment by mrjb** [comment]
We also need to add the "sort" functionality and ultimately the "select-and-strip" functionality (secondary importance) from the explore page to the Alerts and Pip tables. The colouring functionality isn't so important here as there is so much text. The crucial thing though is just to replicate (as close as possible) the current tables with bootstrap tables, so we can start adding in functionality as the project evolves.

**Comment by mixmixmix** [comment]
@mrjb I did the fixes we talked about, ready in branch issue64Buttons.
