### ISSUE TITLE
New Tabs

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#73]
To please include **Mental Health**, **Child Health** and **Vaccination and Nutrition** tabs in the online framework.

**Mental Health**
To include conditions (as with CD, NCD) that appear within category _mhgap_ of the codes file

**Child Health**
To include conditions that appears  within category _imci_ of the codes file

**Vaccination and Nutrition**
To include the childhood vaccinations table that currently appears in the health services tab, and also to include a table covering breastfeeding and nutrition questions in the case report. I will speak with Gunnar when back to understand how to code these in the codes file.

**Comment by Gulfa** [comment]
Mental Health and Child Health is fine. Will need more information about the proposed tables in the Vaccination and Nutrition tab.
