### ISSUE TITLE
Arabic Text in download is not formatted correctly

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#85]
Arabic text in download data is not formatted correctly for some reason. The raw data on the ODK Aggregate server is ok however... if we could please look into how it is handled during download.

**Comment by Gulfa** [comment]
When downloading what data is this problem occurring and what is wrong with the formatting?

**Comment by johnhaskew** [comment]
This is resolved. It was not an issue with the system itself and formatting is preserved.
