### ISSUE TITLE
Reports End Date

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#92]
When choosing the end date e.g. 31 March 2016 on the cover page, the report subsequently generated indicates one day later (e.g. 1 April 2016). 

Could we please change so it reflects the same date (ie. 31 March 2016)

**Comment by johnhaskew** [comment]
any update on this?

**Comment by Gulfa** [comment]
No, has not been a priority

**Comment by johnhaskew** [comment]
I thought in the last discussion that it was a known issue with a minor fix? Clearly we cannot start sharing any reports with such an obvious bug in the report, so it becomes a major issue!

I have no idea when things and realise you guys are constantly managing different requests all the time, but would be great to put estimated timelines on each of these issues to perhaps better allow us to prioritise them.
