### ISSUE TITLE
New Madagascar Report

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#93]
To please create a new report according to the attached template. Please do format / colour as done with the detailed indicator report previously...

[Rapport de Surveillance Epidemiologique Hebdomadaire.docx](https://github.com/meerkat-code/meerkat_frontend/files/265774/Rapport.de.Surveillance.Epidemiologique.Hebdomadaire.docx)

**Comment by mrjb** [comment]
Just having a look into this, and I've got a few questions: 

- The number of "surveillance./diarrhoea" is repeated in two adjacent rows of table 2, is this intended? Presumably the second (going off my minimal French) should be filtered by age?

- The number with ICD code A03 is repeated in two adjacent rows of table 2, under different labels, is this intended?

- The number with ICD code A20 is repeated in rows 15 and 20 of the table, under different labels, is this intended?

- At the moment no code exists in the Madagascar code file for ICD codes E46.10, and A80.10. Are these definitely the correct codes? And if so, where can I get the details of what they represent, so I can add them to our codes file. 

- Do I create a new abacus code just for ICD !00, or do we used the already existing "other" abacus code (pr7, line 36) which also includes a large number other ICD "U" & "Z" among other things.

**Comment by johnhaskew** [comment]
Hi Jonathan, thanks so much for taking a look at this. I was going to write tonight to update on a planning meeting at MOH today to finalise form entry etc:

1. We have decided to include all diseases within case-based entry that will contribute to this report rather than include some in the aggregate daily register. The only information collected in the daily register will now be total fever cases that contribute to this report.

2. I attach a revised report template (with slightly different layout also from MOH) which includes data references now to the case based form.

3. Please also note that deaths are also included within this report now and we have included an extra variable within the case form to determine if the case being submitted is a case or a death (pt./death='mortality')

In answer to your queries:
1. Diarrhoea is now included as a case-based entry (A09) and yes the two rows differ based on of age.
2. Sorry A03 refers to bloody diarrhoea and it was a mistake to include it in two adjacent rows. This is corrected in v3 of the report attached.
3. Another mistake - apologies. A20 refers to Plague only and is corrected in v3 attached.
4. We have created a new codes file (attached) which includes the new code definitions included for E46.10 (Moderate Malnutrition) and A80.10 (AFP) and others.
5. !00 is also included in the new codes file to determine "other / unusual event"

I hope this helps clarify. I am more than happy to Skype tomorrow to go through if it would help or please let me know if any other clarifications are needed.

[mad_codes.xlsx](https://github.com/meerkat-code/meerkat_frontend/files/273320/mad_codes.xlsx)

[Rapport de Surveillance Epidemiologique Hebdomadaire v3.docx](https://github.com/meerkat-code/meerkat_frontend/files/273323/Rapport.de.Surveillance.Epidemiologique.Hebdomadaire.v3.docx)

**Comment by johnhaskew** [comment]
Sorry - please find updated mad_codes.xls to include animal bite (T14.1) also.

[mad_codes.xlsx](https://github.com/meerkat-code/meerkat_frontend/files/273972/mad_codes.xlsx)

**Comment by mrjb** [comment]
Thanks for this. It's really helpful.  A few further queries about the new report design...

- By A80.10 do you mean A80.1? the latter is in the codes file, whereas I don't think the former is.
- A80.10 actually appears twice in table "2b",rows 1 and 4. Is that intended?
- A03 appears twice, but in separate tables 2a (row 1) and 2c (row 3) so perhaps that is intended?
- The new codes file doesn't include a stand alone icd !00 code, but does have the same prc_7 code that was  included in the original codes file. Is this prc_7  (that includes counting the occurrence of ICD "U" & "Z" among other things) the code you want me to use, or did you mean to add a stand alone !00 code to the new codes file?
- "+death" which form variables are these figures sourced from?

**Comment by johnhaskew** [comment]
Hi Jonathan - thank you for your patience with all this.
1. We do mean A80.10 and I attach a new version of the codes file with this included!
2. No this was a mistake and please find new version of the report template attached
3. Another mistake :)
4. !00 is now included in the codes file.

Death is coded as pt./death = ‘yes’ in the data collection form and all variables for causes of death are stored under mortality=' '

I hope this all makes sense and let me know if you need any clarification

[Rapport de Surveillance Epidemiologique Hebdomadaire v3.docx](https://github.com/meerkat-code/meerkat_frontend/files/279879/Rapport.de.Surveillance.Epidemiologique.Hebdomadaire.v3.docx)
[mad_codes.xlsx](https://github.com/meerkat-code/meerkat_frontend/files/279881/mad_codes.xlsx)

**Comment by mrjb** [comment]
Hi John,  A80.10 doesn't seem to appear in the new codes file as a single code, it is listed with a number of other codes in cmd_19 "Acute Flaccid Paralysis".  Do you want cases that just satisfy A80.10? What would that row look like? I think everything else makes sense - I just have to figure out how to do counting based on conditions across three column headings.

**Comment by johnhaskew** [comment]
The reality of the system implementation in Madagascar is that A80.10 is the only code that can be entered currently (we don't allow search for ICD 10 in the current implementation, it is kept very basic).

But we group together just for good practice because any of these codes would generate an AFP alert.

Does that make sense?

**Comment by mrjb** [comment]
Yes I think so.  So I'll use the grouped code cmd_19 there... Many thanks.  I think that's everything now.

**Comment by mrjb** [comment]
Hi John,  Just one final query... How is age being stored given that we're looking for days, months and years?

**Comment by johnhaskew** [comment]
Hi Jonathan - sure. 

pt./age records the age in years
child_age records the age in months for all children less than 5 years.

I can see the issue with the 28 days age category. I think we should change this to 0-1 month (taken from child_age) and than 1-11 months etc.

Hope that's ok

**Comment by johnhaskew** [comment]
Jonathan - the recording of slide / rdt result for malaria and plague is 'positive' not 'yes'. Sorry - i attach an updating template with revised codes.

[Rapport de Surveillance Epidemiologique Hebdomadaire v3.docx](https://github.com/meerkat-code/meerkat_frontend/files/281366/Rapport.de.Surveillance.Epidemiologique.Hebdomadaire.v3.docx)

**Comment by mrjb** [comment]
Wonderful.  Thanks.  I've sorted the back end now, so just laying things out correctly now. 

I can write this report in French for now.  But ultimately the original will need to be hard-coded in English as per the rest of the site, and then translated through the translation system Gunnar is working on. Once that is done, the work I do creating a French report will be binned.   

Could you send me through an English translation of the report as well when you get a chance?  I obviously can just feed it through Google Translate, but phrases like "Death Recapitulation" seem a little strange... There's probably more appropriate ways of phrasing things?

**Comment by johnhaskew** [comment]
Great stuff - thank you Jonathan. Sure - please find the english translation attached and fantastic that we can incorporate translation at some point.

[Rapport de Surveillance Epidemiologique Hebdomadaire v3 EN.docx](https://github.com/meerkat-code/meerkat_frontend/files/282342/Rapport.de.Surveillance.Epidemiologique.Hebdomadaire.v3.EN.docx)

**Comment by mrjb** [comment]
The English version of this report is now deployed.  Can you have a glance at it and let me know of anything that urgently needs changing? Can be access through the usual reports form and from the splash page.

**Comment by mrjb** [comment]
I'll close this issue now, but just let me know if there are any other changes to be made.
