### ISSUE TITLE
Madagascar Download

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#94]
To please format the CD download function in Madagascar according to the attached data dictionary.
[Communicable Disease Download.docx](https://github.com/meerkat-code/meerkat_frontend/files/265776/Communicable.Disease.Download.docx)

**Comment by mrjb** [comment]
Getting a "buffer size" error being thrown by the API: 
`invalid request block size: 6635 (max 4096)...skip`
Gulfa to have a look at it.

**Comment by mrjb** [comment]
Ok this is working in deployment.  I will now close.
