### ISSUE TITLE
Jordan CD and NCD Download

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#95]
To please update the Jordan CD and NCD download function to include additional variables (as attached, the new variables are highlighted in yellow).
[Public Health Surveillance | Data Dictionary Codes.docx](https://github.com/meerkat-code/meerkat_frontend/files/265778/Public.Health.Surveillance.Data.Dictionary.Codes.docx)

**Comment by johnhaskew** [comment]
To please also include BMI in the NCD download function (revised codes file attached).

[Public Health Surveillance | Data Dictionary Codes.docx](https://github.com/meerkat-code/meerkat_frontend/files/292729/Public.Health.Surveillance.Data.Dictionary.Codes.docx)

**Comment by johnhaskew** [comment]
I note that BMI is not yet included in the download if we can please include

**Comment by mrjb** [comment]
How is BMI calculated in our context?  Is it just a case of including the lab_3 variable from the jordan codes file? Or do you want something different?

**Comment by mrjb** [comment]
This is finished.
