### ISSUE TITLE
Madagascar Malaria Report

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#97]
Please find attached the template for malaria report in Madagascar. Do let me know if any clarifications are needed.

[Rapport de Surveillance Epidemiologique Hebdomadaire du Paludisme v1.docx](https://github.com/meerkat-code/meerkat_frontend/files/281379/Rapport.de.Surveillance.Epidemiologique.Hebdomadaire.du.Paludisme.v1.docx)

**Comment by mrjb** [comment]
Can I get an English version of this as well please?

**Comment by johnhaskew** [comment]
Sure - please find attached. Thanks Jonathan. Please note an additional column is included in Table 1 to reflect RDT positive or negative (the rapid test for malaria).

So to record RDT positive or negative for simple, severe and malaria deaths... (in table 1)

Just let me know if you need any clarifications.

[Rapport de Surveillance Epidemiologique Hebdomadaire du Paludisme v1 EN.docx](https://github.com/meerkat-code/meerkat_frontend/files/295823/Rapport.de.Surveillance.Epidemiologique.Hebdomadaire.du.Paludisme.v1.EN.docx)

**Comment by mrjb** [comment]
Hi John, Are the `surveillance./consultations` and `surveillance./fever` columns in the mad case form?  Can they be equal to a number higher than 0 or 1? Can you confirm that the age for these cases is given in the `child_age` and `pt./age` columns?

**Comment by johnhaskew** [comment]
Hi Jonathan - the consultations and fever columns are in the register form, and sorry there are listed as intro./consultation and intro/.fever in the register form. My mistake.

Yes than can be higher than 0 or 1.

Yes age is child_age or pt./age from the case report

**Comment by mrjb** [comment]
Hi John, Little confused about this. I don't believe the top two rows of the table are possible then? It's surely not possible to break data from the daily register down by age taken from the case report form...

**Comment by johnhaskew** [comment]
Er yes indeed! Again my oversight! In which case could I propose to include a Total columns for age-groups and to include the total consultations / fever cases here from the register because you are quite right we can't break this down right now.

I will speak with MOH as we may need to edit the register to include age break down in future

**Comment by mrjb** [comment]
Not entirely clear on how you're envisaging this total column to work. I understand the concept of a total column across the age groups. Not sure about how the daily register consultations and fever count fits into this?

**Comment by johnhaskew** [comment]
Something like the attached?

[Rapport de Surveillance Epidemiologique Hebdomadaire du Paludisme v2 EN.docx](https://github.com/meerkat-code/meerkat_frontend/files/307316/Rapport.de.Surveillance.Epidemiologique.Hebdomadaire.du.Paludisme.v2.EN.docx)

**Comment by mrjb** [comment]
Ah great.  Though presumably there's the same problem with breaking down consultations and pregnant women?

**Comment by johnhaskew** [comment]
er yes! so please blank out in the same way. i'm glad there is another pair of eyes on all this.

**Comment by mrjb** [comment]
Almost finished this.  How are we counting "all" malaria cases? Do we count all occurrences of cd./malaria_rdt and cd./malaria_slide?

**Comment by johnhaskew** [comment]
Great - thanks so much Jonathan.
Yes but all malaria cases means all cases that are either RDT or slide positive

**Comment by mrjb** [comment]
There's presumably a reason why the malaria report is only interested in children over 2 months or older? It's just making the totals look a little odd, because the totals I think are including  some cases for younger than one month (though I've not confirmed this yet, it could be an error in my code).  

This is almost there now. I just have to write a proper test for it, so that I can make sure numbers are being calculated properly, etc...

**Comment by johnhaskew** [comment]
Hi Jonathan - wonderful thanks so much. 

I didn't even see that and yes we need to correct. could you please include 0 - 2 months as a separate column? it is good to ensure all totals add up.

**Comment by mrjb** [comment]
This is deployed. Let me know of anything that's urgently wrong.  I am aware of the following that still needs to be done:
-We will need to translate the new strings.
-The consultations figure for some spurious reason doesn't match that on the front page.  Not really clear on why at the moment, but will look into it.

**Comment by johnhaskew** [comment]
Wonderful the Malaria Report is there! – thank you! Some comments if that is ok:
1.	Translation doesn’t seem to be applied fully? Only in some places?
2.	Please could we name the report:
- Malaria Epidemiological Surveillance Report (for English)
- Rapport de Surveillance Épidémiologique du Paludisme (for French)
3.	Apologies for the change but **Number of RDT tests performed** is now being calculated from the Daily Register variable _intro./rdt_ and from the Case Report. Could we please change *
4.	Could we please use a lighter shade of grey for the boxes that are blanked out. Even just leaving the same row colour but with no content is ok.

* @Gulfa regarding the _intro./rdt_ variable. This was included later so some register will not have a value recorded. Could we please ensure that any register with no _intro./rdt_ recorded be changed so that it equals the number recorded in _intro./fever_?

**Comment by johnhaskew** [comment]
Thanks Jonathan:
1. No I don't mean to calculate from both. I mean to just calculate the number of RDT tests performed based on the daily register variable _intro./rdt_ (as we do to calculate the number of fever cases).
2. Ok - no problem. I take your advice and we keep it as it is!

Thank you.

**Comment by mrjb** [comment]
Thanks for the quick response.
As I understand it, the total number of RDT tests could therefore be different to the sum of the broken down data (by sex/age etc...) because they are coming from two different data sources. Does this mean you want me to remove these breakdown cells like we have done for the consultations row and the fever row?

**Comment by johnhaskew** [comment]
Ah sorry. Yes please - as we cannot disaggregate this number either now.

**Comment by mrjb** [comment]
With you.  Will do.

**Comment by mrjb** [comment]
I am assuming that the intro./rdt data is just an integer number of RDT tests that need to be summed like the consultations and fever cases... let me know if this is wrong.

**Comment by johnhaskew** [comment]
Yes that's right

**Comment by mrjb** [comment]
I think I agree with @johnhaskew  - I prefer a lighter shade of grey for the empty cells.  I've change the shade to match the header and key columns. It should be included in the next deployment.  Other than that I believe this issue is now closed.
