### ISSUE TITLE
Change location level for selector in subscribe form

### ISSUE THREAD

**Issue by mrjb** [meerkat-code/meerkat_frontend#98]
Location level needs to be district for madagascar and region for jordan.

**Comment by mrjb** [comment]
Just to be clear on this @johnhaskew in madagascar you want to be able to sign up to either notifications from the whole country, or notifications from one district. Signing up to notifications for regions/individual clininics/multiple districts are all not necessary/low priority issues?

**Comment by johnhaskew** [comment]
Ultimately it would be great to be able to select any level - central (All), region, district, down to individual clinic - but realise this may not be possible operationally or easy with UI etc.

The level of alert notification and response in Madagascar is the district (whereas in Jordan it is region), so if it is easiest for now to select just one district or the whole country that is fine. Would be nice to ultimately select multiple districts (i.e. for a region) eventually but this is not a priority - we have enough to do!

**Comment by mrjb** [comment]
I have decided to do this properly:  you can now select any single location from the location tree using the standard location selector which is referenced in the form.  (So you can received alerts for a single clinic as well as districts, regions and the entire country). All alerts are published in abacus at all location levels: clinic, district and region. This update will be in the next deployment of the madagascar site (should be redeployed today, all going well).
